import { getTodaysBrief } from "@/lib/intelligence/queries";
import { EmptyState } from "@/components/dashboard/EmptyState";

export const dynamic = "force-dynamic";

export default async function IntelligencePage() {
  const brief = await getTodaysBrief();

  return (
    <div className="space-y-6">
      <header>
        <p className="eyebrow">Intelligence</p>
        <h1 className="font-display text-2xl text-ink-100 mt-1">Daily Intelligence Brief</h1>
        <p className="text-sm text-ink-500 mt-1">
          Generated automatically once a day from the highest-scoring analyzed events.
        </p>
      </header>

      {!brief ? (
        <EmptyState
          title="No brief yet"
          hint="Generated by /api/cron/briefings once there is at least one analyzed event in the last 24 hours. Weekly reports (§31) follow the same pattern — see the brief generator in lib/ai/generate-brief.ts as the template to extend."
        />
      ) : (
        <div className="space-y-6">
          <section className="panel p-5">
            <p className="eyebrow mb-3">Today's 5 Most Important Developments</p>
            <ol className="space-y-3 list-decimal list-inside">
              {brief.topDevelopments.map((d, i) => (
                <li key={i} className="text-sm">
                  <span className="text-ink-100 font-medium">{d.headline}</span>
                  <p className="text-ink-500 ml-5 mt-0.5">{d.whyItMatters}</p>
                </li>
              ))}
            </ol>
          </section>

          <div className="grid grid-cols-3 gap-4">
            {[
              ["Kenya Implications", brief.kenyaImplications],
              ["Regional Implications", brief.regionalImplications],
              ["Global Implications", brief.globalImplications],
            ].map(([label, text]) => (
              <div key={label} className="panel p-4">
                <p className="eyebrow mb-2">{label}</p>
                <p className="text-sm text-ink-300">{text}</p>
              </div>
            ))}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="panel p-4">
              <p className="eyebrow mb-2 text-signal-risk">Emerging Risks</p>
              <ul className="text-sm text-ink-300 space-y-1 list-disc list-inside">
                {brief.emergingRisks.map((r, i) => <li key={i}>{r}</li>)}
              </ul>
            </div>
            <div className="panel p-4">
              <p className="eyebrow mb-2 text-signal-opportunity">Emerging Opportunities</p>
              <ul className="text-sm text-ink-300 space-y-1 list-disc list-inside">
                {brief.emergingOpportunities.map((o, i) => <li key={i}>{o}</li>)}
              </ul>
            </div>
          </div>

          <div className="panel p-4">
            <p className="eyebrow mb-2">What to Watch Next</p>
            <ul className="text-sm text-ink-300 space-y-1 list-disc list-inside">
              {brief.whatToWatchNext.map((w, i) => <li key={i}>{w}</li>)}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
}
