import type { Event } from "@/types";
import { LevelBadge, ScoreBar } from "./ScoreBadge";

// Answers, in order: what's changing (title/summary), why it matters
// (businessImplication), who's affected (affectedSectors + Kenya impact
// badge), what could happen next (timeHorizon/futureSignal), and what
// opportunity/risk to watch (potentialOpportunities/potentialRisks) — the
// five questions this whole tool exists to answer. Every field it uses was
// already being generated by the AI analysis step; most just weren't
// rendered anywhere before.
export function EventCard({ event }: { event: Event }) {
  const topRisk = event.potentialRisks?.[0];
  const topOpportunity = event.potentialOpportunities?.[0];
  const primarySource = event.sources?.[0];

  return (
    <article className="panel p-4 space-y-3">
      {/* What's changing */}
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="eyebrow">{event.domains.join(" · ")}</p>
          <h3 className="font-display text-base text-ink-100 mt-1 leading-snug">{event.title}</h3>
        </div>
        <LevelBadge level={event.impact.directKenyaImpact} label={`Kenya: ${event.impact.directKenyaImpact}`} />
      </div>

      <p className="text-sm text-ink-300 leading-relaxed">{event.summary}</p>

      {/* Why it matters */}
      {event.businessImplication && (
        <p className="text-sm text-ink-100 leading-relaxed border-l-2 border-base-700 pl-3">
          {event.businessImplication}
        </p>
      )}

      {/* Who's affected */}
      <div className="flex flex-wrap gap-2">
        {event.affectedSectors.slice(0, 4).map((s) => (
          <span key={s} className="text-[11px] font-mono px-2 py-0.5 rounded bg-base-800 text-ink-500">
            {s}
          </span>
        ))}
      </div>

      <div className="grid grid-cols-3 gap-3 pt-2 border-t border-base-700">
        <ScoreBar label="Importance" value={event.scores.importance} tone="info" />
        <ScoreBar label="Risk" value={event.scores.riskScore} tone="risk" />
        <ScoreBar label="Opportunity" value={event.scores.opportunityScore} tone="opportunity" />
      </div>

      {/* What opportunity/risk to watch */}
      {(topRisk || topOpportunity) && (
        <div className="space-y-1.5 pt-1 text-xs">
          {topOpportunity && (
            <p className="text-signal-opportunity">
              <span className="font-mono uppercase tracking-wide text-[10px] mr-1.5">Opportunity</span>
              {topOpportunity}
            </p>
          )}
          {topRisk && (
            <p className="text-signal-risk">
              <span className="font-mono uppercase tracking-wide text-[10px] mr-1.5">Risk</span>
              {topRisk}
            </p>
          )}
        </div>
      )}

      {/* What could happen next, and where this came from */}
      <div className="flex items-center justify-between text-[11px] font-mono text-ink-500 pt-1">
        <span>Future signal: {event.scores.futureSignal}/100 · {event.impact.timeHorizon.replace("_", " ")}</span>
        {primarySource && (
          <a
            href={primarySource.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-ink-500 hover:text-ink-100 underline underline-offset-2"
          >
            {primarySource.sourceName} ↗
          </a>
        )}
      </div>
    </article>
  );
}
