import type { Source } from "@/types";

// ============================================================================
// SOURCE REGISTRY SEED (§6-14, §45)
// This is the MASTER source registry covering the Business Trend Watch
// blueprint across Kenya, East Africa, Africa, regional trade blocs,
// global trade, geopolitics, shipping, commodities, investment,
// technology, climate, labour and sector intelligence.
//
// Tier 1 = frequent automated monitoring (official/critical)
// Tier 2 = regular monitoring (regional/trade bodies)
// Tier 3 = slower, strategic/contextual monitoring
//
// ACTIVE STATUS — READ BEFORE FLIPPING active: true ON A SOURCE BELOW:
// Currently 10 sources are `active: true`: 7 verified in earlier passes
// (Central Bank of Kenya, Business Daily Africa, The East African,
// COMESA, AllAfrica, gCaptain, FreightWaves) plus WTO (re-verified with
// its actual documented feed after an earlier pass wrongly gave up on
// it), European Central Bank, and Federal Reserve. Everything else is
// deliberately `active: false`, for one of two reasons (stated on the
// `active:` line itself):
//   1. "collectionMethod not implemented" — collectionMethod is anything
//      OTHER than "rss" or "web_scrape" (api, pdf, csv, email_alert,
//      manual). Only lib/collectors/rss.ts and lib/collectors/
//      web-scrape.ts exist right now (see IMPLEMENTED_COLLECTION_METHODS
//      in lib/collectors/rss.ts).
//   2. "confirmed broken RSS endpoint" — has collectionMethod "rss" but
//      was verified (via live production errors, not guessing) to not
//      have a working feed: East African Community (404, no alternative
//      found) and IMF (403, bot-blocked regardless of URL). WTO was
//      previously in this category too but has since been fixed with its
//      actual documented feed URL — see its entry below.
// web_scrape IS now implemented (CSS-selector based, zero AI cost — see
// lib/collectors/web-scrape.ts), but that doesn't mean every web_scrape
// source below will work the moment you flip it to active: the generic
// fallback heuristic only handles simple page layouts reliably. Before
// activating one: set its scrapeSelector to a real CSS selector checked
// against the source's actual page, or activate it as-is and watch its
// first "Run pipeline now" result — a "matched 0 items" error tells you
// exactly which sources need a selector.
// Most of the 133 entries below were bulk-added from a broader watchlist
// document without individually verifying each has a real, fetchable
// source — many (e.g. "White House", "UN Security Council", "Panama
// Canal Authority") are topics/entities from that list, not confirmed
// publishers. Verify before activating — see the README's "Extending the
// source network" section.
// ============================================================================

export const SEED_SOURCES: Omit<Source, "id" | "createdAt">[] = [
  // ==========================================================================
  // KENYA — GOVERNMENT & POLICY
  // ==========================================================================

  {
    name: "Office of the President of Kenya",
    organization: "Office of the President",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "geopolitics"],
    category: "Government / Executive",
    website: "https://www.president.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Parliament of Kenya",
    organization: "Parliament of Kenya",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "regulation"],
    category: "Government / Legislature",
    website: "https://www.parliament.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Assembly of Kenya",
    organization: "National Assembly",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "regulation"],
    category: "Government / Legislature",
    website: "https://www.parliament.go.ke/the-national-assembly",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Senate of Kenya",
    organization: "Senate of Kenya",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "regulation"],
    category: "Government / Legislature",
    website: "https://www.parliament.go.ke/the-senate",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Law",
    organization: "National Council for Law Reporting",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "regulation"],
    category: "Law / Legislation",
    website: "https://new.kenyalaw.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Office of the Attorney General of Kenya",
    organization: "Office of the Attorney General",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "regulation"],
    category: "Government / Legal Affairs",
    website: "https://www.statelaw.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Treasury of Kenya",
    organization: "National Treasury",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "government_policy"],
    category: "Government / Finance",
    website: "https://www.treasury.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "State Department for Trade",
    organization: "State Department for Trade",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "trade_logistics", "government_policy"],
    category: "Government / Trade",
    website: "https://www.trade.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Labour and Social Protection",
    organization: "Ministry of Labour and Social Protection",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "labour", "government_policy"],
    category: "Government / Labour",
    website: "https://labour.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Transport",
    organization: "Ministry of Transport",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "trade_logistics", "infrastructure_investment"],
    category: "Government / Transport",
    website: "https://www.transport.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Agriculture and Livestock Development",
    organization: "Ministry of Agriculture and Livestock Development",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "agriculture", "commodity"],
    category: "Government / Agriculture",
    website: "https://kilimo.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Energy and Petroleum",
    organization: "Ministry of Energy and Petroleum",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "energy", "commodity"],
    category: "Government / Energy",
    website: "https://energy.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of ICT and Digital Economy",
    organization: "Ministry of ICT and Digital Economy",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "technology", "digital_trade"],
    category: "Government / Technology",
    website: "https://ict.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Tourism and Wildlife",
    organization: "Ministry of Tourism and Wildlife",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "tourism", "sector"],
    category: "Government / Tourism",
    website: "https://www.tourism.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Health Kenya",
    organization: "Ministry of Health",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "healthcare", "sector"],
    category: "Government / Health",
    website: "https://www.health.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Ministry of Environment Kenya",
    organization: "Ministry of Environment",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "climate", "environment"],
    category: "Government / Environment",
    website: "https://environment.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Council of Governors Kenya",
    organization: "Council of Governors",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "sector"],
    category: "County Government",
    website: "https://cog.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // KENYA — ECONOMY & REGULATORS
  // ==========================================================================

  {
    name: "Central Bank of Kenya — Press Releases",
    organization: "Central Bank of Kenya",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "monetary_policy"],
    category: "Government / Monetary Policy",
    website: "https://www.centralbank.go.ke",
    rssEndpoint: "https://www.centralbank.go.ke/feed/",
    collectionMethod: "rss",
    updateFrequencyMinutes: 60,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: true,
    active: true,
  },
  {
    name: "Kenya National Bureau of Statistics",
    organization: "KNBS",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "sector", "economic_data"],
    category: "Economic Data",
    website: "https://www.knbs.or.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Revenue Authority",
    organization: "KRA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "trade_logistics", "taxation", "regulation"],
    category: "Revenue / Customs",
    website: "https://www.kra.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Competition Authority of Kenya",
    organization: "Competition Authority of Kenya",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "regulation", "sector"],
    category: "Competition Regulation",
    website: "https://www.cak.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Capital Markets Authority Kenya",
    organization: "CMA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "investment"],
    category: "Financial Regulation",
    website: "https://www.cma.or.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Insurance Regulatory Authority Kenya",
    organization: "IRA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "insurance", "regulation"],
    category: "Financial Regulation",
    website: "https://www.ira.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Retirement Benefits Authority Kenya",
    organization: "RBA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "labour"],
    category: "Financial Regulation",
    website: "https://www.rba.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "SACCO Societies Regulatory Authority",
    organization: "SASRA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "regulation"],
    category: "Financial Regulation",
    website: "https://www.sasra.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Energy and Petroleum Regulatory Authority",
    organization: "EPRA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "energy", "regulation", "commodity"],
    category: "Energy Regulation",
    website: "https://www.epra.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Communications Authority of Kenya",
    organization: "CA Kenya",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "technology", "telecommunications", "regulation"],
    category: "Technology Regulation",
    website: "https://www.ca.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Investment Authority",
    organization: "KenInvest",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "investment", "infrastructure_investment"],
    category: "Investment Promotion",
    website: "https://invest.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Export Promotion and Branding Agency",
    organization: "KEPROBA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "trade_logistics", "export"],
    category: "Trade Promotion",
    website: "https://makeitkenya.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Micro and Small Enterprises Authority",
    organization: "MSEA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "sector", "investment"],
    category: "SME Development",
    website: "https://msea.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Public Procurement Regulatory Authority",
    organization: "PPRA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "government_policy", "procurement"],
    category: "Procurement Regulation",
    website: "https://ppra.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // KENYA — BUSINESS & PRIVATE SECTOR
  // ==========================================================================

  {
    name: "Business Daily Africa",
    organization: "Nation Media Group",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "trade_logistics", "sector"],
    category: "Business News",
    website: "https://www.businessdailyafrica.com",
    rssEndpoint: "https://www.businessdailyafrica.com/service/rss/bd/1939136/feed.rss",
    collectionMethod: "rss",
    updateFrequencyMinutes: 30,
    tier: 1,
    reliabilityRating: 80,
    authorityRating: 60,
    machineReadable: true,
    active: true,
  },
  {
    name: "Kenya Private Sector Alliance",
    organization: "KEPSA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "business", "sector", "government_policy"],
    category: "Private Sector Association",
    website: "https://kepsa.or.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya National Chamber of Commerce and Industry",
    organization: "KNCCI",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "business", "trade_logistics", "sector"],
    category: "Chamber of Commerce",
    website: "https://www.kenyachamber.or.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Association of Manufacturers",
    organization: "KAM",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "manufacturing", "sector", "trade_logistics"],
    category: "Manufacturing Association",
    website: "https://www.kam.co.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Federation of Kenya Employers",
    organization: "FKE",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "labour", "business"],
    category: "Employers Association",
    website: "https://www.fke-kenya.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Bankers Association",
    organization: "KBA",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "finance", "banking", "sector"],
    category: "Banking Association",
    website: "https://www.kba.co.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // LABOUR & TRADE UNIONS
  // ==========================================================================

  {
    name: "Central Organization of Trade Unions (COTU-K)",
    organization: "COTU-K",
    country: "Kenya",
    region: "East Africa",
    domains: ["labour"],
    category: "Labour / Trade Unions",
    website: "https://cotu-kenya.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 75,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Employment and Labour Relations Court",
    organization: "Employment and Labour Relations Court",
    country: "Kenya",
    region: "East Africa",
    domains: ["labour", "regulation", "kenya"],
    category: "Labour Court",
    website: "https://elrc.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // EAST AFRICA — EAC
  // ==========================================================================

  {
    name: "East African Community — News",
    organization: "EAC Secretariat",
    country: "Tanzania",
    region: "East Africa",
    domains: ["east_africa", "trade_logistics"],
    category: "Regional Body",
    website: "https://www.eac.int",
    rssEndpoint: "https://www.eac.int/rss",
    collectionMethod: "rss",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: true,
    active: false, // auto-deactivated: confirmed broken RSS endpoint, no working alternative found
  },
  {
    name: "The East African (Nation Media)",
    organization: "Nation Media Group",
    country: "Kenya",
    region: "East Africa",
    domains: ["east_africa", "trade_logistics"],
    category: "Regional News",
    website: "https://www.theeastafrican.co.ke",
    rssEndpoint: "https://www.theeastafrican.co.ke/rss.xml",
    collectionMethod: "rss",
    updateFrequencyMinutes: 60,
    tier: 2,
    reliabilityRating: 78,
    authorityRating: 60,
    machineReadable: true,
    active: true,
  },
  {
    name: "EAC Trade Information Portal",
    organization: "East African Community",
    country: "Tanzania",
    region: "East Africa",
    domains: ["east_africa", "trade_logistics", "customs"],
    category: "Regional Trade Portal",
    website: "https://tradehelpdesk.eac.int",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // EAST AFRICAN COUNTRIES
  // ==========================================================================

  {
    name: "Bank of Uganda",
    organization: "Bank of Uganda",
    country: "Uganda",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://www.bou.or.ug",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Bank of Tanzania",
    organization: "Bank of Tanzania",
    country: "Tanzania",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://www.bot.go.tz",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Bank of Rwanda",
    organization: "National Bank of Rwanda",
    country: "Rwanda",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://www.bnr.rw",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Bank of South Sudan",
    organization: "Bank of South Sudan",
    country: "South Sudan",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://boss.gov.ss",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Bank of Ethiopia",
    organization: "National Bank of Ethiopia",
    country: "Ethiopia",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data", "trade_logistics"],
    category: "Central Bank",
    website: "https://www.nbe.gov.et",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Bank of Rwanda",
    organization: "National Bank of Rwanda",
    country: "Rwanda",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://www.bnr.rw",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "National Bank of Somalia",
    organization: "Central Bank of Somalia",
    country: "Somalia",
    region: "East Africa",
    domains: ["east_africa", "finance", "economic_data"],
    category: "Central Bank",
    website: "https://centralbank.gov.so",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // AFRICA — REGIONAL TRADE BLOCS
  // ==========================================================================

  {
    name: "African Continental Free Trade Area (AfCFTA) Secretariat",
    organization: "AfCFTA Secretariat",
    country: "Ghana",
    region: "Africa",
    domains: ["africa", "trade_logistics"],
    category: "Trade Bloc",
    website: "https://au-afcfta.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "African Union",
    organization: "African Union",
    country: "Ethiopia",
    region: "Africa",
    domains: ["africa", "government_policy", "geopolitics"],
    category: "Continental Institution",
    website: "https://au.int",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "COMESA — News & Events",
    organization: "COMESA Secretariat",
    country: "Zambia",
    region: "Africa",
    domains: ["africa", "trade_logistics"],
    category: "Trade Bloc",
    website: "https://www.comesa.int",
    rssEndpoint: "https://www.comesa.int/feed/",
    collectionMethod: "rss",
    updateFrequencyMinutes: 720,
    tier: 3,
    reliabilityRating: 85,
    authorityRating: 95,
    machineReadable: true,
    active: true,
  },
  {
    name: "SADC — Latest News",
    organization: "SADC Secretariat",
    country: "Botswana",
    region: "Africa",
    domains: ["africa", "trade_logistics", "geopolitics"],
    category: "Trade Bloc",
    website: "https://www.sadc.int/latest-news",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "IGAD",
    organization: "Intergovernmental Authority on Development",
    country: "Djibouti",
    region: "Africa",
    domains: ["africa", "east_africa", "geopolitics", "trade_logistics"],
    category: "Regional Organization",
    website: "https://igad.int",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Tripartite Free Trade Area — COMESA EAC SADC",
    organization: "COMESA-EAC-SADC Tripartite",
    country: "Africa",
    region: "Africa",
    domains: ["africa", "trade_logistics"],
    category: "Tripartite Trade Bloc",
    website: "https://www.comesa.int",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 85,
    authorityRating: 95,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GLOBAL TRADE & ECONOMIC INSTITUTIONS
  // ==========================================================================

  {
    name: "World Trade Organization — News",
    organization: "WTO",
    country: "Switzerland",
    region: "Global",
    domains: ["global", "trade_logistics"],
    category: "International Institution",
    website: "https://www.wto.org",
    // CORRECTED — a previous pass concluded WTO had no working feed, but
    // that was based on trying wrong/guessed URLs (?rss=1, old /library/
    // rss/ path assumed dead). WTO's OWN "Resources > RSS feeds gateway"
    // page (wto.org/english/res_e/webcas_e/rss_e.htm) currently documents
    // this exact URL as "All WTO news" — first-party source, not a guess.
    // My verification tooling couldn't confirm it live (WTO's robots.txt
    // blocks automated fetching from where I checked), so watch this
    // source's first production run closely — if it 404s or times out,
    // deactivate again and note the actual error here.
    rssEndpoint: "https://www.wto.org/library/rss/latest_news_e.xml",
    collectionMethod: "rss",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: true,
    active: true,
  },
  {
    name: "IMF — Press Releases",
    organization: "International Monetary Fund",
    country: "United States",
    region: "Global",
    domains: ["global", "finance"],
    category: "International Institution",
    website: "https://www.imf.org",
    // Old URL (imf.org/en/News/RSS?Language=ENG) is a dead/renamed path
    // that now 403s. Current feed lives at /en/news/rss.
    rssEndpoint: "https://www.imf.org/en/news/rss",
    collectionMethod: "rss",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: true,
    active: false, // auto-deactivated: confirmed broken RSS endpoint, no working alternative found
  },
  {
    name: "World Bank",
    organization: "World Bank",
    country: "United States",
    region: "Global",
    domains: ["global", "africa", "finance", "development"],
    category: "International Development Institution",
    website: "https://www.worldbank.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "UN Trade and Development",
    organization: "UNCTAD",
    country: "Switzerland",
    region: "Global",
    domains: ["global", "trade_logistics", "africa"],
    category: "International Trade Institution",
    website: "https://unctad.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "UN Comtrade",
    organization: "United Nations Statistics Division",
    country: "United States",
    region: "Global",
    domains: ["global", "trade_logistics", "economic_data"],
    category: "International Trade Data",
    website: "https://comtradeplus.un.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: true,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "International Trade Centre",
    organization: "ITC",
    country: "Switzerland",
    region: "Global",
    domains: ["global", "trade_logistics", "africa"],
    category: "International Trade Institution",
    website: "https://www.intracen.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "African Development Bank",
    organization: "AfDB",
    country: "Côte d'Ivoire",
    region: "Africa",
    domains: ["africa", "finance", "investment", "infrastructure_investment"],
    category: "Development Bank",
    website: "https://www.afdb.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "International Finance Corporation",
    organization: "IFC",
    country: "United States",
    region: "Global",
    domains: ["global", "africa", "investment"],
    category: "Development Finance",
    website: "https://www.ifc.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "OECD",
    organization: "Organisation for Economic Co-operation and Development",
    country: "France",
    region: "Global",
    domains: ["global", "finance", "trade_logistics"],
    category: "International Economic Institution",
    website: "https://www.oecd.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GLOBAL NEWS
  // ==========================================================================

  {
    name: "Reuters — Africa",
    organization: "Reuters",
    country: "United Kingdom",
    region: "Global",
    domains: ["global", "africa"],
    category: "Global News",
    website: "https://www.reuters.com/world/africa/",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 60,
    tier: 1,
    reliabilityRating: 85,
    authorityRating: 70,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "AllAfrica — Business",
    organization: "AllAfrica",
    country: "Africa",
    region: "Africa",
    domains: ["africa", "sector"],
    category: "Pan-African Business News",
    website: "https://allafrica.com/business/",
    rssEndpoint: "https://allafrica.com/tools/headlines/rdf/business/headlines.rdf",
    collectionMethod: "rss",
    updateFrequencyMinutes: 60,
    tier: 2,
    reliabilityRating: 80,
    authorityRating: 70,
    machineReadable: true,
    active: true,
  },

  // ==========================================================================
  // SHIPPING & MARITIME
  // ==========================================================================

  {
    name: "International Maritime Organization",
    organization: "IMO",
    country: "United Kingdom",
    region: "Global",
    domains: ["trade_logistics", "shipping", "geopolitics"],
    category: "Maritime Institution",
    website: "https://www.imo.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "gCaptain — Maritime & Shipping News",
    organization: "gCaptain",
    country: "Global",
    region: "Global",
    domains: ["trade_logistics", "global"],
    category: "Shipping & Maritime",
    website: "https://gcaptain.com",
    rssEndpoint: "https://feeds.feedburner.com/gcaptain",
    collectionMethod: "rss",
    updateFrequencyMinutes: 60,
    tier: 2,
    reliabilityRating: 85,
    authorityRating: 75,
    machineReadable: true,
    active: true,
  },
  {
    name: "Maersk",
    organization: "A.P. Moller - Maersk",
    country: "Denmark",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Shipping Company",
    website: "https://www.maersk.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "MSC Mediterranean Shipping Company",
    organization: "MSC",
    country: "Switzerland",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Shipping Company",
    website: "https://www.msc.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "CMA CGM",
    organization: "CMA CGM",
    country: "France",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Shipping Company",
    website: "https://www.cma-cgm.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Hapag-Lloyd",
    organization: "Hapag-Lloyd",
    country: "Germany",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Shipping Company",
    website: "https://www.hapag-lloyd.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "COSCO Shipping",
    organization: "COSCO Shipping",
    country: "China",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Shipping Company",
    website: "https://www.coscoshipping.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // KENYA PORTS & CORRIDORS
  // ==========================================================================

  {
    name: "Kenya Ports Authority — News",
    organization: "KPA",
    country: "Kenya",
    region: "East Africa",
    domains: ["trade_logistics", "infrastructure_investment"],
    category: "Ports & Logistics",
    website: "https://www.kpa.co.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 92,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "LAPSSET Corridor Development Authority",
    organization: "LAPSSET",
    country: "Kenya",
    region: "East Africa",
    domains: ["trade_logistics", "infrastructure_investment", "east_africa"],
    category: "Trade Corridor",
    website: "https://www.lapsset.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Railways",
    organization: "Kenya Railways",
    country: "Kenya",
    region: "East Africa",
    domains: ["trade_logistics", "infrastructure_investment"],
    category: "Rail / Logistics",
    website: "https://krc.co.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya Airports Authority",
    organization: "KAA",
    country: "Kenya",
    region: "East Africa",
    domains: ["trade_logistics", "infrastructure_investment", "aviation"],
    category: "Aviation Infrastructure",
    website: "https://www.kaa.go.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kenya National Highways Authority",
    organization: "KeNHA",
    country: "Kenya",
    region: "East Africa",
    domains: ["trade_logistics", "infrastructure_investment"],
    category: "Road Infrastructure",
    website: "https://kenha.co.ke",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // AFRICAN PORTS
  // ==========================================================================

  {
    name: "Dar es Salaam Port",
    organization: "Tanzania Ports Authority",
    country: "Tanzania",
    region: "East Africa",
    domains: ["trade_logistics", "shipping", "infrastructure_investment"],
    category: "African Port",
    website: "https://www.ports.go.tz",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 92,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Tanga Port",
    organization: "Tanzania Ports Authority",
    country: "Tanzania",
    region: "East Africa",
    domains: ["trade_logistics", "shipping", "infrastructure_investment"],
    category: "African Port",
    website: "https://www.ports.go.tz",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Djibouti Ports",
    organization: "Djibouti Ports and Free Zones Authority",
    country: "Djibouti",
    region: "Horn of Africa",
    domains: ["trade_logistics", "shipping", "infrastructure_investment"],
    category: "African Port",
    website: "https://dpfza.gov.dj",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 90,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Berbera Port",
    organization: "DP World",
    country: "Somaliland",
    region: "Horn of Africa",
    domains: ["trade_logistics", "shipping", "infrastructure_investment"],
    category: "African Port",
    website: "https://www.dpworld.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Durban Port",
    organization: "Transnet National Ports Authority",
    country: "South Africa",
    region: "Southern Africa",
    domains: ["trade_logistics", "shipping", "infrastructure_investment"],
    category: "African Port",
    website: "https://www.transnet.net",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 92,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Walvis Bay Corridor",
    organization: "Walvis Bay Corridor Group",
    country: "Namibia",
    region: "Southern Africa",
    domains: ["trade_logistics", "infrastructure_investment", "africa"],
    category: "Trade Corridor",
    website: "https://www.wbcg.com.na",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Lobito Corridor",
    organization: "Lobito Corridor",
    country: "Angola",
    region: "Southern Africa",
    domains: ["trade_logistics", "infrastructure_investment", "africa"],
    category: "Trade Corridor",
    website: "https://lobitocorridor.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GLOBAL TRADE ROUTES
  // ==========================================================================

  {
    name: "Suez Canal Authority",
    organization: "Suez Canal Authority",
    country: "Egypt",
    region: "Middle East / Africa",
    domains: ["trade_logistics", "shipping", "geopolitics"],
    category: "Global Trade Route",
    website: "https://www.suezcanal.gov.eg",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Panama Canal Authority",
    organization: "Panama Canal Authority",
    country: "Panama",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Global Trade Route",
    website: "https://pancanal.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "IMO Red Sea Maritime Watch",
    organization: "International Maritime Organization",
    country: "United Kingdom",
    region: "Global",
    domains: ["trade_logistics", "shipping", "geopolitics"],
    category: "Maritime Security",
    website: "https://www.imo.org/en/mediacentre/hottopics/pages/red-sea.aspx",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 180,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GLOBAL TRADE & LOGISTICS — RATES, POLICY TRACKING & TRADE PRESS
  // The maritime/shipping-line block above covers carriers and chokepoints;
  // this covers the freight-cost, protectionism, and customs-facilitation
  // signals an economics/finance-minded reader actually watches — container
  // rate benchmarks move ahead of import cost inflation, and trade-measure
  // trackers flag tariff/NTB risk before it shows up in official data.
  // ==========================================================================

  {
    name: "Freightos Baltic Index (FBX)",
    organization: "Freightos",
    country: "United States",
    region: "Global",
    domains: ["trade_logistics", "shipping", "economic_data"],
    category: "Freight Rate Benchmark",
    website: "https://terminal.freightos.com/fbx-freightos-baltic-index/",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 85,
    authorityRating: 80,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Baltic Exchange — Dry & Wet Indices",
    organization: "Baltic Exchange",
    country: "United Kingdom",
    region: "Global",
    domains: ["trade_logistics", "shipping", "economic_data", "commodity"],
    category: "Freight Rate Benchmark",
    website: "https://www.balticexchange.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Drewry — World Container Index",
    organization: "Drewry Shipping Consultants",
    country: "United Kingdom",
    region: "Global",
    domains: ["trade_logistics", "shipping", "economic_data"],
    category: "Freight Rate Benchmark",
    website: "https://www.drewry.co.uk/world-container-index-assessed-by-drewry",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 85,
    authorityRating: 80,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Kiel Trade Indicator",
    organization: "Kiel Institute for the World Economy",
    country: "Germany",
    region: "Global",
    domains: ["trade_logistics", "shipping", "economic_data", "global"],
    category: "Trade Volume Estimate",
    website: "https://www.ifw-kiel.de/publications/kiel-trade-indicator/",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 10080,
    tier: 3,
    reliabilityRating: 80,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Global Trade Alert",
    organization: "Global Trade Alert (University of St. Gallen)",
    country: "Switzerland",
    region: "Global",
    domains: ["trade_logistics", "government_policy", "regulation", "geopolitics"],
    category: "Trade Policy & Protectionism Tracker",
    website: "https://www.globaltradealert.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 88,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "World Customs Organization — Newsroom",
    organization: "WCO",
    country: "Belgium",
    region: "Global",
    domains: ["trade_logistics", "customs", "regulation", "global"],
    category: "Customs & Trade Facilitation",
    website: "https://www.wcoomd.org/en/media/newsroom.aspx",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 90,
    authorityRating: 95,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Journal of Commerce (JOC)",
    organization: "S&P Global",
    country: "United States",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Trade & Logistics Press",
    website: "https://www.joc.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 3,
    reliabilityRating: 82,
    authorityRating: 75,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Lloyd's List",
    organization: "Lloyd's List (Informa)",
    country: "United Kingdom",
    region: "Global",
    domains: ["trade_logistics", "shipping", "global"],
    category: "Trade & Logistics Press",
    website: "https://lloydslist.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 3,
    reliabilityRating: 82,
    authorityRating: 78,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "FreightWaves",
    organization: "FreightWaves",
    country: "United States",
    region: "Global",
    domains: ["trade_logistics", "shipping", "economic_data", "global"],
    category: "Trade & Logistics Press",
    website: "https://www.freightwaves.com",
    rssEndpoint: "https://www.freightwaves.com/news/feed",
    collectionMethod: "rss",
    updateFrequencyMinutes: 180,
    tier: 3,
    reliabilityRating: 80,
    authorityRating: 72,
    machineReadable: true,
    active: true,
  },

  // ==========================================================================
  // COMMODITIES
  // ==========================================================================

  {
    name: "International Energy Agency",
    organization: "IEA",
    country: "France",
    region: "Global",
    domains: ["global", "energy", "commodity"],
    category: "Energy Intelligence",
    website: "https://www.iea.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Food and Agriculture Organization",
    organization: "FAO",
    country: "Italy",
    region: "Global",
    domains: ["global", "agriculture", "commodity", "food_security"],
    category: "Agriculture / Food",
    website: "https://www.fao.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "International Coffee Organization",
    organization: "ICO",
    country: "United Kingdom",
    region: "Global",
    domains: ["global", "commodity", "agriculture"],
    category: "Commodity Organization",
    website: "https://ico.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "International Tea Committee",
    organization: "International Tea Committee",
    country: "United Kingdom",
    region: "Global",
    domains: ["global", "commodity", "agriculture"],
    category: "Commodity Organization",
    website: "https://inttea.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 3,
    reliabilityRating: 85,
    authorityRating: 85,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // UNITED STATES
  // ==========================================================================

  {
    name: "White House",
    organization: "Executive Office of the President",
    country: "United States",
    region: "North America",
    domains: ["global", "geopolitics", "government_policy"],
    category: "Government / Executive",
    website: "https://www.whitehouse.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "U.S. Trade Representative",
    organization: "USTR",
    country: "United States",
    region: "North America",
    domains: ["global", "trade_logistics", "government_policy"],
    category: "Trade Policy",
    website: "https://ustr.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "U.S. Department of Commerce",
    organization: "U.S. Department of Commerce",
    country: "United States",
    region: "North America",
    domains: ["global", "trade_logistics", "sector"],
    category: "Government / Commerce",
    website: "https://www.commerce.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "U.S. Treasury",
    organization: "U.S. Department of the Treasury",
    country: "United States",
    region: "North America",
    domains: ["global", "finance", "geopolitics"],
    category: "Government / Finance",
    website: "https://home.treasury.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Federal Reserve",
    organization: "Federal Reserve System",
    country: "United States",
    region: "North America",
    domains: ["global", "finance", "monetary_policy"],
    category: "Central Bank",
    website: "https://www.federalreserve.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "U.S. International Trade Commission",
    organization: "USITC",
    country: "United States",
    region: "North America",
    domains: ["global", "trade_logistics"],
    category: "Trade Commission",
    website: "https://www.usitc.gov",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // EUROPEAN UNION
  // ==========================================================================

  {
    name: "European Commission",
    organization: "European Commission",
    country: "Belgium",
    region: "Europe",
    domains: ["global", "government_policy", "trade_logistics"],
    category: "Regional Government",
    website: "https://commission.europa.eu",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "European Commission — Trade",
    organization: "European Commission",
    country: "Belgium",
    region: "Europe",
    domains: ["global", "trade_logistics", "regulation"],
    category: "Trade Policy",
    website: "https://policy.trade.ec.europa.eu",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "European Central Bank",
    organization: "ECB",
    country: "Germany",
    region: "Europe",
    domains: ["global", "finance", "monetary_policy"],
    category: "Central Bank",
    website: "https://www.ecb.europa.eu",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Eurostat",
    organization: "European Commission",
    country: "Luxembourg",
    region: "Europe",
    domains: ["global", "economic_data", "trade_logistics"],
    category: "Economic Data",
    website: "https://ec.europa.eu/eurostat",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: true,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // CHINA
  // ==========================================================================

  {
    name: "Ministry of Commerce of China",
    organization: "MOFCOM",
    country: "China",
    region: "Asia",
    domains: ["global", "trade_logistics", "government_policy"],
    category: "Trade Ministry",
    website: "https://english.mofcom.gov.cn",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "People's Bank of China",
    organization: "PBOC",
    country: "China",
    region: "Asia",
    domains: ["global", "finance", "monetary_policy"],
    category: "Central Bank",
    website: "http://www.pbc.gov.cn",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "China-Africa Relations",
    organization: "Government of China",
    country: "China",
    region: "Asia",
    domains: ["global", "africa", "investment", "geopolitics"],
    category: "China-Africa Relations",
    website: "https://www.fmprc.gov.cn",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // INDIA
  // ==========================================================================

  {
    name: "India Ministry of Commerce and Industry",
    organization: "Government of India",
    country: "India",
    region: "Asia",
    domains: ["global", "trade_logistics", "government_policy"],
    category: "Trade Ministry",
    website: "https://commerce.gov.in",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Reserve Bank of India",
    organization: "RBI",
    country: "India",
    region: "Asia",
    domains: ["global", "finance", "monetary_policy"],
    category: "Central Bank",
    website: "https://www.rbi.org.in",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // MIDDLE EAST
  // ==========================================================================

  {
    name: "UAE Government",
    organization: "Government of UAE",
    country: "United Arab Emirates",
    region: "Middle East",
    domains: ["global", "investment", "trade_logistics"],
    category: "Government",
    website: "https://u.ae",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "DP World",
    organization: "DP World",
    country: "United Arab Emirates",
    region: "Middle East",
    domains: ["global", "trade_logistics", "investment", "shipping"],
    category: "Global Logistics Company",
    website: "https://www.dpworld.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 90,
    authorityRating: 90,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Saudi Government",
    organization: "Government of Saudi Arabia",
    country: "Saudi Arabia",
    region: "Middle East",
    domains: ["global", "investment", "energy", "geopolitics"],
    category: "Government",
    website: "https://www.my.gov.sa",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Qatar Government",
    organization: "Government of Qatar",
    country: "Qatar",
    region: "Middle East",
    domains: ["global", "investment", "energy"],
    category: "Government",
    website: "https://www.gov.qa",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "Oman Government",
    organization: "Government of Oman",
    country: "Oman",
    region: "Middle East",
    domains: ["global", "investment", "trade_logistics"],
    category: "Government",
    website: "https://www.oman.om",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // INVESTMENT & DEVELOPMENT
  // ==========================================================================

  {
    name: "United Nations Industrial Development Organization",
    organization: "UNIDO",
    country: "Austria",
    region: "Global",
    domains: ["global", "africa", "manufacturing", "investment"],
    category: "Industrial Development",
    website: "https://www.unido.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "United Nations Economic Commission for Africa",
    organization: "UNECA",
    country: "Ethiopia",
    region: "Africa",
    domains: ["africa", "economic_data", "trade_logistics", "investment"],
    category: "African Economic Institution",
    website: "https://www.uneca.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // TECHNOLOGY
  // ==========================================================================

  {
    name: "International Telecommunication Union",
    organization: "ITU",
    country: "Switzerland",
    region: "Global",
    domains: ["global", "technology", "digital_trade"],
    category: "Technology Institution",
    website: "https://www.itu.int",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // CLIMATE & ENVIRONMENT
  // ==========================================================================

  {
    name: "United Nations Environment Programme",
    organization: "UNEP",
    country: "Kenya",
    region: "Global",
    domains: ["global", "climate", "environment", "trade_logistics"],
    category: "Environmental Institution",
    website: "https://www.unep.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // SECTOR — AGRICULTURE
  // ==========================================================================

  {
    name: "International Fund for Agricultural Development",
    organization: "IFAD",
    country: "Italy",
    region: "Global",
    domains: ["global", "africa", "agriculture", "investment"],
    category: "Agriculture / Development",
    website: "https://www.ifad.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 1440,
    tier: 2,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GLOBAL FINANCE
  // ==========================================================================

  {
    name: "Bank of England",
    organization: "Bank of England",
    country: "United Kingdom",
    region: "Europe",
    domains: ["global", "finance", "monetary_policy"],
    category: "Central Bank",
    website: "https://www.bankofengland.co.uk",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 2,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // BROAD AFRICAN BUSINESS
  // ==========================================================================

  {
    name: "African Business",
    organization: "African Business",
    country: "United Kingdom",
    region: "Africa",
    domains: ["africa", "business", "sector", "investment"],
    category: "African Business News",
    website: "https://african.business",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 120,
    tier: 2,
    reliabilityRating: 82,
    authorityRating: 70,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // GEOPOLITICAL / GLOBAL CONTEXT
  // ==========================================================================

  {
    name: "United Nations",
    organization: "United Nations",
    country: "United States",
    region: "Global",
    domains: ["global", "geopolitics", "government_policy"],
    category: "International Organization",
    website: "https://www.un.org",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "UN Security Council",
    organization: "United Nations Security Council",
    country: "United States",
    region: "Global",
    domains: ["global", "geopolitics", "security"],
    category: "International Security",
    website: "https://www.un.org/securitycouncil",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 1,
    reliabilityRating: 98,
    authorityRating: 100,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },

  // ==========================================================================
  // SOCIAL / PROFESSIONAL SIGNALS
  // LinkedIn entries are intentionally represented as web sources. LinkedIn
  // is treated as a secondary signal layer rather than primary authority.
  // ==========================================================================

  {
    name: "LinkedIn — Kenya Private Sector",
    organization: "LinkedIn",
    country: "Kenya",
    region: "East Africa",
    domains: ["kenya", "business", "sector"],
    category: "Professional / Business Signals",
    website: "https://www.linkedin.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 360,
    tier: 3,
    reliabilityRating: 65,
    authorityRating: 50,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "LinkedIn — African Business",
    organization: "LinkedIn",
    country: "Africa",
    region: "Africa",
    domains: ["africa", "business", "sector"],
    category: "Professional / Business Signals",
    website: "https://www.linkedin.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 3,
    reliabilityRating: 65,
    authorityRating: 50,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "LinkedIn — Global Business",
    organization: "LinkedIn",
    country: "Global",
    region: "Global",
    domains: ["global", "business", "sector"],
    category: "Professional / Business Signals",
    website: "https://www.linkedin.com",
    collectionMethod: "web_scrape",
    updateFrequencyMinutes: 720,
    tier: 3,
    reliabilityRating: 65,
    authorityRating: 50,
    machineReadable: false,
    active: false, // auto-deactivated: collectionMethod not implemented
  },
  {
    name: "European Central Bank — Press Releases",
    organization: "European Central Bank",
    country: "Eurozone",
    region: "Global",
    domains: ["global"],
    category: "Central Bank",
    website: "https://www.ecb.europa.eu",
    // Verified live — a search actually returned real, current XML
    // content from this exact URL (RSS 2.0, items dated Apr 2026), not
    // just a documentation page claiming it exists.
    rssEndpoint: "https://www.ecb.europa.eu/rss/press.xml",
    collectionMethod: "rss",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: true,
    active: true,
  },
  {
    name: "Federal Reserve — Monetary Policy Press Releases",
    organization: "Board of Governors of the Federal Reserve System",
    country: "United States",
    region: "Global",
    domains: ["global"],
    category: "Central Bank",
    website: "https://www.federalreserve.gov",
    // Verified via search results showing real, current (2026-dated)
    // press release titles served from this exact feed URL.
    rssEndpoint: "https://www.federalreserve.gov/feeds/press_monetary.xml",
    collectionMethod: "rss",
    updateFrequencyMinutes: 720,
    tier: 1,
    reliabilityRating: 95,
    authorityRating: 100,
    machineReadable: true,
    active: true,
  },
];